services:
  inventory-service:
    build:
      context: .
      args:
        JAR_FILE: inventory-service/target/inventory-service.jar
  login-service:
    build:
      context: .
      args:
        JAR_FILE: login-service/target/login-service.jar
  client-gateway:
    build:
      context: .
      args:
        JAR_FILE: client-gateway/target/client-gateway.jar
    ports:
      - "8443:8443"
    env_file:
      - .env
    depends_on:
      - inventory-service
      - login-service