services:
  inventory-service:
    build:
      context: .
      args:
        JAR_FILE: inventory-service/target/inventory-service.jar
    ports:
      - "8081:8080"
  login-service:
    build:
      context: .
      args:
        JAR_FILE: login-service/target/login-service.jar
    ports:
      - "8082:8080"