server:
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_STORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: tomcat
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://auth-service:8080
              predicates:
                - Path=/auth/**
            - id: inventory-service
              uri: http://inventory-service:8080
              predicates:
                - Path=/inventory/**
              filters:
                - RemoveRequestHeader=X-User-Id
                - AuthenticateBySessionToken=X-User-Id
                - RemoveRequestHeader=Authorization